### ISSUE TITLE
PHP Version?

### ISSUE THREAD

**Issue by PadawanTony** [codeburrow/diplohack#43]
Riz I tried to clone the repository and I got this error:

```
    - sebastian/object-enumerator 1.0.0 requires php >=5.6 -> your PHP version (5.5.12) does not satisfy that requirement.
```

**Comment by rdok** [comment]
PHP ends security supports the upcoming July. [Source](http://php.net/supported-versions.php)  
As such it is a good idea to update your PHP version of your development machine, as well as any production servers.  
I would suggest to bumb it up to PHP 7.0 as it has some amazing performance results. [Source](http://www.zend.com/en/resources/php7_infographic)

**Comment by PadawanTony** [comment]
Nai ok. Let's have a workshop on how to do that.

**Comment by rdok** [comment]
Sure, anytime let me know. If you're using homestead/vagrant is quite easy: https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04
