### ISSUE TITLE
Seed data.

### ISSUE THREAD

**Issue by rdok** [codeburrow/diplohack#7]

**Comment by Kontaxi123** [comment]
[Diplohack_Funds+EU-Gr.xlsx](https://github.com/codeburrow/diplohack/files/211172/Diplohack_Funds.EU-Gr.xlsx)

**Comment by Kontaxi123** [comment]
[Diplohack_9april2016.xlsx](https://github.com/codeburrow/diplohack/files/211393/Diplohack_9april2016.xlsx)
